### ISSUE TITLE
页面停留时间过长，或内容已提交，请刷新页面

### ISSUE THREAD

**Issue by Panni007** [wecenter/wecenter#18]
页面停留时间过长，或内容已提交，请刷新页面

出现情况：在上传几张图片之后，提示错误，页面停留时间不超过5min，望解决，同时希望加入已输入内容的备份功能

**Comment by NeverMin** [comment]
如果你是使用 Linux 的话, 看 /var/log/apache/error.log 有没有异常的日志,

另外"已输入内容的备份功能"你是指草稿功能吗? 请详细说明之. 谢谢


-Never

2015-03-10 20:40 GMT+08:00 Jimmy Zhou <notifications@github.com>:

**Comment by jat001** [comment]
不是 bug，有草稿功能。
