### ISSUE TITLE
从社交平台新建创建的用户如果名字带有 / 会造成 URL 错误 (3.1.0)

### ISSUE THREAD

**Issue by NeverMin** [wecenter/wecenter#20]
URL 找不到此用户
http://ask.otrs.org.cn/people//Fty%E5%91%88%E6%9B%A6

用户名在这里倒数第二个:
http://ask.otrs.org.cn/people/page-19

他的名字是: /ty呈曦

我的想法是, 现在这位先从后台拿掉 /, 之后在生成帐号时用正则把 / 换掉.

**Comment by jat001** [comment]
测试了新浪微博，没这问题。
http://ask.otrs.org.cn/people/%2Fty%E5%91%88%E6%9B%A6 无法访问是因为你的伪静态规则有问题

**Comment by NeverMin** [comment]
@Jat 我先到后台找一下原因, 找到解决方法时再关闭此 issue, 感谢你这么快回复.

-Never

2015-03-21 1:29 GMT+08:00 Jat <notifications@github.com>:
