### ISSUE TITLE
HTTPS.ckeditor.js:77

### ISSUE THREAD

**Issue by NeverMin** [wecenter/wecenter#21]
Mixed Content: The page at 'https://ask.otrs.org.cn/publish/' was loaded over HTTPS, but requested an insecure script 'http://cdn.jsdelivr.net/ace/1.1.4/noconflict/ace.js'. This request has been blocked; the content must be served over HTTPS.ckeditor.js:77 CKEDITOR.tools.extend.append

wecenter 3.1.0 版本, 启用全 https 环境之后, 无法加载非 https ckeditor.js 脚本(由于内含了一个http的连接)

**Comment by NeverMin** [comment]
@jat001 /wecenter/static/js/editor/ckeditor/plugins/pbckcode/plugin.js 第37行, 我直接改了.

**Comment by jat001** [comment]
https://github.com/wecenter/wecenter/commit/7422bd8afc83c1826af36273b3fc8d9617f33360
