### ISSUE TITLE
官方有考慮增加繁體中文嗎？

### ISSUE THREAD

**Issue by LNDDYL** [wecenter/wecenter#22]

**Comment by jat001** [comment]
阁下您好：
鉴于简繁之间并不存在像中英之间那样巨大的差异，且使用繁中的 WeCenter 用户并不多，所以这个提议不会被考虑。
另外简繁之间的转换可以由程序自动完成，且质量尚可，人工翻译费时费力。

**Comment by NeverMin** [comment]
@Jat 是否有可能这样, 把 Core 全部换成英文(我可以协助), 然后简中换成外挂的方式, 例如 zh_CN 和 zh_TW, 不知道
@LNDDYL 有不有兴趣维护繁中语言?

-Never

2015-05-25 13:23 GMT+08:00 Jat <notifications@github.com>:

**Comment by jat001** [comment]
@NeverMin 简繁转换在前端就可完成，且无需人工维护，如有需要请自行开发。

**Comment by LNDDYL** [comment]
@NeverMin 我有興趣維護繁中

**Comment by LNDDYL** [comment]
將WeCenter推廣至港澳台地區，難道不好嗎？

**Comment by NeverMin** [comment]
我的想法是把现在 wecenter 核心部分的语言换成英文的:

现在:
<?php _e('本站点会员注册需要经过管理员审核,请耐心等待'); ?><br />

换成:
<?php _e('This site membership registration is awaiting moderation, please
be patient'); ?><br />

然后写一段脚本去历遍所有的文件, 生成空白的语言文件. 所有语言除英文外都是外挂. 假如有人拉一个西班牙语也很方面.


-Never


2015-05-29 16:05 GMT+08:00 LNDDYL <notifications@github.com>:

**Comment by explon** [comment]
这样工程可能会太浩大，因为每个版本都有文字需要进行改动

**Comment by jat001** [comment]
@LNDDYL @NeverMin 如 @explon 所说，如果只是简繁转换的话，我还是建议由程序完成，而其他语言的翻译，确实不是一两个人能够维护的。

**Comment by NeverMin** [comment]
@Jat 或是我花些时间出来用, 到时我拉一个 PR 给你.

2015-05-29 17:35 GMT+08:00 Jat <notifications@github.com>:

**Comment by LNDDYL** [comment]
@jat001 我願意去翻譯！

**Comment by LNDDYL** [comment]
簡繁之間差距很大的，只是你不知道而已，差距在於詞語的表達上。

**Comment by LNDDYL** [comment]
@NeverMin PR是什麼？

**Comment by NeverMin** [comment]
github 的协助模式. 即我派生一份源码之后将我的改动提交到原分支合并. 由于近段搬家(从一个城市到另一个城市), 可能需要一段时间哦.


-Never

2015-06-01 15:12 GMT+08:00 LNDDYL <notifications@github.com>:

**Comment by LNDDYL** [comment]
我怎麼參與翻譯啊？ @NeverMin  @jat001

**Comment by NeverMin** [comment]
@LNDDYL 你有按以下的方式做了吗?
http://wenda.wecenter.com/question/9225
