### ISSUE TITLE
如果OAuth登陆邮箱与注册邮箱时不一致，就会无法登陆

### ISSUE THREAD

**Issue by skywalker512** [wecenter/wecenter#31]
例如:注册时用的是xxxx@hotmail.com,而google的登陆邮箱为xxxx@gmail.com这就造成已经绑定但第3方登陆时仍然提醒绑定！（也有可能是google的用户名与注册用户名不一致）=》(但facebook用户名就不一样，一样可以认证)
![](http://ww3.sinaimg.cn/mw690/005HmEMjgw1evfv4ux53wj30dc06v74h.jpg)
![](http://ww2.sinaimg.cn/mw690/005HmEMjgw1evfv4xe1jij30dz0d374q.jpg)

**Comment by jat001** [comment]
不明白什么意思，不是靠邮箱判断的，检查 aws_users_facebook aws_users_google 等表。

**Comment by skywalker512** [comment]
我尝试的看了一下,但看不出什么所以然来,下面是aws_users_google表的数据
![2015-08-27 08 46 39](https://cloud.githubusercontent.com/assets/12960906/9510010/d8759708-4c98-11e5-963b-20597cc6a370.png)
suot
![2015-08-27 08 39 06](https://cloud.githubusercontent.com/assets/12960906/9509991/9f9595b4-4c98-11e5-8c85-e3c87689b57e.png)

**Comment by jat001** [comment]
你是不是说：wecenter 账号已绑定 google 账号，用同一个 google 账号再登录的时候，还提示绑定？

**Comment by skywalker512** [comment]
是的
