### ISSUE TITLE
query_all写错了

### ISSUE THREAD

**Issue by Someant** [wecenter/wecenter#32]
```bash
ststem/aws_model.inc.php #547 query_all()
````
```php
	public function query_all($sql, $limit = null, $offset = null, $where = null, $group_by = null)
	{

		$this->slave();

		if (!$sql)
		{
			throw new Exception('Query was empty.');
		}

		if ($where)
		{
			$sql .= ' WHERE ' . $where;
		}

		if ($group_by)
		{
			$sql .= " GROUP BY `" . $this->quote($group_by) . "`";
		}

		if ($limit)
		{
			$sql .= ' LIMIT ' . $limit;
		}

		if ($offset)
		{
			$sql .= ' OFFSET ' . $limit;
		}

		if (AWS_APP::config()->get('system')->debug)
		{
			$start_time = microtime(TRUE);
		}
		//var_dump($sql);
		try {
			$result = $this->db()->fetchAll($sql);
		} catch (Exception $e) {
			show_error("Database error\n------\n\nSQL: {$sql}\n\nError Message: " . $e->getMessage(), $e->getMessage());
		}

		if (AWS_APP::config()->get('system')->debug)
		{
			AWS_APP::debug_log('database', (microtime(TRUE) - $start_time), $sql);
		}

		return $result;
	}


//change->
		if ($offset)
		{
			$sql .= ' OFFSET ' . $offset;
		}
```
OFFSET写错了 将导致使用query_all方法无法正常翻页

**Comment by explon** [comment]
谢谢报告，这个 SQL 拼接只是 DEBUG 的时候查询，并不执行，下个版本修正

发件人:  Someant
答复:  wecenter/wecenter
日期:  2015年9月1日 星期二 09:47
至:  wecenter/wecenter
主题:  [wecenter] query_all写错了 (#32)

ststem/aws_model.inc.php #547 query_all()````bash
```php    public function query_all($sql, $limit = null, $offset = null, $where = null, $group_by = null)    {        $this->slave();        if (!$sql)        {            throw new Exception('Query was empty.');        }        if ($where)        {            $sql .= ' WHERE ' . $where;        }        if ($group_by)        {            $sql .= " GROUP BY `" . $this->quote($group_by) . "`";        }        if ($limit)        {            $sql .= ' LIMIT ' . $limit;        }        if ($offset)        {            $sql .= ' OFFSET ' . $limit;        }        if (AWS_APP::config()->get('system')->debug)        {            $start_time = microtime(TRUE);        }        //var_dump($sql);        try {            $result = $this->db()->fetchAll($sql);        } catch (Exception $e) {            show_error("Database error\n------\n\nSQL: {$sql}\n\nError Message: " . $e->getMessage(), $e->getMessage());        }        if (AWS_APP::config()->get('system')->debug)        {            AWS_APP::debug_log('database', (microtime(TRUE) - $start_time), $sql);        }        return $result;    }//change->        if ($offset)        {            $sql .= ' OFFSET ' . $offset;        }```php

**Comment by jat001** [comment]
https://github.com/wecenter/wecenter/commit/e6f5a84fba75a1dd8b6fbd8d12469afba9d05f90
