### ISSUE TITLE
models/geo.php距离计算有错误.

### ISSUE THREAD

**Issue by shellvon** [wecenter/wecenter#35]
这里 => https://github.com/wecenter/wecenter/blob/master/models/geo.php#L73
乘多少不应该除以多少么?

**Comment by explon** [comment]
这个函数有 Bug, 下个版本会改进

**Comment by jat001** [comment]
9fec0698cb374339f9a8c9c49b31f40ddea4789f

**Comment by shellvon** [comment]
Thanks.我又在该行注释了一下，麻烦你看看呢～
