### ISSUE TITLE
希望解决Ajax翻页后退问题：（

### ISSUE THREAD

**Issue by ideager** [wecenter/wecenter#39]
感谢提供WC这个开源程序，目前在本地测试体验中发现几点问题，其中翻页功能最为糟糕，遇到兴趣的内容点击进去再后退又得重头翻看，另外收藏夹栏目名不能修改:(
还有部分代码没有规范，文件夹结构也可再优化下，主题文件也有几处小错误，具体位置当时修正后没有标记，日后发现再提交！

**Comment by luckyfish0826** [comment]
是啊，我也在解决。 欢迎交流！
