### ISSUE TITLE
會考慮重定向話題嗎？

### ISSUE THREAD

**Issue by ckc** [wecenter/wecenter#42]
了解官方擔心相似話題的問題不考慮
個人覺得這是解決無歧異的同名詞，而非近義詞
例如大陸地區的微信，海外無論是否華人市場均稱WeChat、深大=>深圳大學 這種情況

**Comment by zhengqiang** [comment]
?考??合并功能

?自我的 iPhone

在 2016年2月17日，00:57，ckc <notifications@github.com<mailto:notifications@github.com>> ?道：


了解官方擔心相似話題的問題不考慮
個人覺得這是解決無歧異的同名詞，而非近義詞
例如大陸地區的微信，海外無論是否華人市場均稱WeChat、深大=>深圳大學 這種情況

**Comment by jat001** [comment]
有这功能。
