### ISSUE TITLE
Message: Unable to set session handler

### ISSUE THREAD

**Issue by Lagolas** [wecenter/wecenter#45]
你好，安装后访问首页，报错
Message: Unable to set session handler

Application error
------
Message: Unable to set session handler
------
Build: 3.1.8 20150226
PHP Version: 
User Agent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
------
Zend_Session_Exception: Unable to set session handler in /public_html/chat/system/Zend/Session.php:283
Stack trace:
#0 /public_html/chat/system/aws_app.inc.php(127): Zend_Session::setSaveHandler(Object(Zend_Session_SaveHandler_DbTable))
#1 /public_html/chat/system/aws_app.inc.php(55): AWS_APP::init()
#2 /public_html/chat/index.php(23): AWS_APP::run()
#3 {main}

我发现论坛上好多人询问，但是没有人回答如何解决。
谢谢！

**Comment by explon** [comment]
关闭 PHP.INI 里的 session_autostart

发自我的 iPhone
