### ISSUE TITLE
sso登录后无限重定向bug

### ISSUE THREAD

**Issue by laotan** [wecenter/wecenter#50]
通过微博或自建的第三方账号体系登录，部分用户会在授权页面无限重定向

一步步排查，数据库aws_user有写入数据，只是页面无法写入session cookie

解决办法是修改此用户的 `salt`值

概率事件，非必现

**Comment by jat001** [comment]
能否提供 request header 和 response header？

**Comment by laotan** [comment]
近期没遇到，之前遇到了只是解决问题，没深究原因，再遇到定位清楚提交PR过来吧
