### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by NeverMin** [wecenter/wecenter#52]
404 error
/static/js/editor/ckeditor/skins/bootstrapck/icons.png

ref in:
/var/www/html/ask.otrs.org.cn/static/js/editor/ckeditor/skins/bootstrapck/editor.css

**Comment by NeverMin** [comment]
@jat001 请问 404 是有意为之吗? 我从上游1[]补齐 icons.png 测试会重影, 即有两层 icons. 但为了避免 404, 我放了一个透明背景图片替换之. editor.css 是编译后的, 不好处理. #


[1]
https://github.com/Kunstmaan/BootstrapCK-Skin/blob/master/icons.png

**Comment by jat001** [comment]
@caprikk

**Comment by caprikk** [comment]
@NeverMin 图片删掉是故意处理的, 为了解决icon的冲突, 直接修改编辑器里面的css工作量太大了

**Comment by odit** [comment]
@caprikk 
ok, Smart way.
可以考虑用透明背景? 免得 404
