### ISSUE TITLE
更新工单之后 ajax 并没有把之前提交的内容清空.

### ISSUE THREAD

**Issue by NeverMin** [wecenter/wecenter#53]
![提交演示](https://cloud.githubusercontent.com/assets/2797432/17391320/ac50d454-5a47-11e6-873c-d0b1135f95bf.gif)

Debug 看到是自动保存草稿引起的:
`{"rsm":null,"errno":1,"err":"\u5df2\u4fdd\u5b58\u8349\u7a3f, 13:08:34"}`

`{rsm: null, errno: 1, err: "已保存草稿, 13:08:34"}
err
:
"已保存草稿, 13:08:34"
errno
:
1
rsm
:
null`

URL:
`/account/ajax/save_draft/item_id-3__type-ticket_reply`

和

`/ticket/ajax/reply/`

如果需要测试环境请找我. 谢谢.

**Comment by jat001** [comment]
出现这个问题不是因为草稿，草稿已在 https://github.com/wecenter/wecenter/blob/enterprise/app/ticket/ajax.php#L126 清除。
原因是发布回复后未清除输入框。
@caprikk

**Comment by jat001** [comment]
4bfc56f
