### ISSUE TITLE
How to play the English language for the site?

### ISSUE THREAD

**Issue by yuri25** [wecenter/wecenter#61]
如何發揮該網站的英語？

How to play the English language for the site?
Help me please.

**Comment by ckc** [comment]
It seems have English language pack under the language folder
/system/init.php, finding similar with this line //define('SYSTEM_LANG', 'en_US');”

**Comment by yuri25** [comment]
Thank you!

**Comment by ckc** [comment]
反過來英文native的設計會比較好
現在擴展其它語言都比較麻煩 還要是js
