### ISSUE TITLE
在某些系统上会引发curl_init()函数找不到bug

### ISSUE THREAD

**Issue by luckyfish0826** [wecenter/wecenter#62]
Message: Call to undefined function curl_init()

我的环境是ubuntu 14。还没有找到解决办法。

**Comment by luckyfish0826** [comment]
我说的是 system/Services/VideoUrlParser.php  这个  Line: 385

**Comment by gouchaoer** [comment]
那是你系统没安装curl扩展，你php -m查一下就知道了

**Comment by luckyfish0826** [comment]
感谢！我原来是php5,然后升级成了php7, 然后不知道怎么回事，安装了7.1版本的curl模块，就装载不了。
后面依次卸载了所有版本的curl，最后解决了。谢谢大家！
